name: palpites_da_loteria
description: Projeto para gerar jogos e verificar resultados dos concursos da loteria.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 4.2.1+29

environment:
  sdk: ">=2.19.0 <3.0.0"

module:
  androidX: true # Add this line.


dependencies:
  flutter:
    sdk: flutter
  animations: ^2.0.7
  cupertino_icons: ^1.0.5
  date_format: ^2.0.7
  device_info_plus: ^8.2.0
  dio: ^5.1.1
  dio_cache_interceptor: ^3.4.2
  easy_dynamic_theme: ^2.2.0
  firebase_analytics: ^10.2.0
  firebase_core: ^2.9.0
  firebase_crashlytics: ^3.1.0
  firebase_messaging: ^14.6.1
  fluttertoast: ^8.2.1
  google_mobile_ads: ^2.4.0
  group_button: ^5.2.2
  http: ^0.13.5
  in_app_review: ^2.0.6
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.0
  provider: ^6.0.5
  reorderables: ^0.6.0
  share_plus: ^6.3.2
  shared_preferences: ^2.1.0
  sqflite: ^2.2.6
  firebase_auth: ^4.6.2
  cloud_firestore: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
